export const companyIndustryTypes = [
  { label: "Agriculture", value: "AGRICULTURE" },
  { label: "Automotive", value: "AUTOMOTIVE" },
  { label: "Banking & Financial Services", value: "BANKING_FINANCIAL_SERVICES" },
  { label: "Biotechnology", value: "BIOTECHNOLOGY" },
  { label: "Construction", value: "CONSTRUCTION" },
  { label: "Consumer Goods", value: "CONSUMER_GOODS" },
  { label: "Education", value: "EDUCATION" },
  { label: "Energy & Utilities", value: "ENERGY_UTILITIES" },
  { label: "Entertainment & Media", value: "ENTERTAINMENT_MEDIA" },
  { label: "Environmental Services", value: "ENVIRONMENTAL_SERVICES" },
  { label: "Food & Beverage", value: "FOOD_BEVERAGE" },
  { label: "Healthcare & Pharmaceuticals", value: "HEALTHCARE_PHARMACEUTICALS" },
  { label: "Hospitality & Tourism", value: "HOSPITALITY_TOURISM" },
  { label: "Information Technology (IT)", value: "INFORMATION_TECHNOLOGY" },
  { label: "Insurance", value: "INSURANCE" },
  { label: "Legal Services", value: "LEGAL_SERVICES" },
  { label: "Logistics & Supply Chain", value: "LOGISTICS_SUPPLY_CHAIN" },
  { label: "Manufacturing", value: "MANUFACTURING" },
  { label: "Marketing & Advertising", value: "MARKETING_ADVERTISING" },
  { label: "Nonprofit & NGO", value: "NONPROFIT_NGO" },
  { label: "Real Estate", value: "REAL_ESTATE" },
  { label: "Retail & E-commerce", value: "RETAIL_ECOMMERCE" },
  { label: "Telecommunications", value: "TELECOMMUNICATIONS" },
  { label: "Transportation", value: "TRANSPORTATION" },
  { label: "Aerospace & Defense", value: "AEROSPACE_DEFENSE" },
  { label: "Mining & Metals", value: "MINING_METALS" },
  { label: "Government & Public Sector", value: "GOVERNMENT_PUBLIC_SECTOR" },
  { label: "Human Resources & Staffing", value: "HUMAN_RESOURCES_STAFFING" },
  { label: "Arts & Design", value: "ARTS_DESIGN" },
  { label: "Research & Development", value: "RESEARCH_DEVELOPMENT" },
] as const;
